### ISSUE TITLE
Remove day1 directory

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#14]
I currently see a duplication of material in these two folders:
* [day1](https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/tree/main/docs/day1)
* https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/tree/main/docs/day1_z_Afternoon

I _think_ we can delete the first one... except its readme. It's necessary for the TOC

**Comment by zoccoler** [comment]
I agree. I just removed it in bd2dd6914895a360dd3047dbf1bc3bcffd3861ea.
Closing this issue then. There is another readme in day1z_Afternoon.
