### ISSUE TITLE
Split day2 content

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#15]
The notebooks in this folder: 
https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/tree/main/docs/day2

Should be partially moved to this folder
https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/tree/main/docs/day2e_Deep_Learning_Segmentation

**Comment by haesleinhuepf** [comment]
@jo-mueller Hey Johannes, could you please take care of this issue? Thanks!

**Comment by jo-mueller** [comment]
Closed by #26
