### ISSUE TITLE
bring day5 in 2-level structure

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#20]
Hi Johannes @jo-mueller ,

would you mind converting day5 into a lower-level folder structure as discussed in #2 ? 

This folder
https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/tree/main/docs/day5/01_points_and_surfaces

should be something like 
docs/day5a_points_and_surfaces

Thanks!
Robert

**Comment by haesleinhuepf** [comment]
Also please, add this session to the TOC. 

Thanks!

**Comment by jo-mueller** [comment]
Should be fine now - I'll close the issue when I see the toc compiled correctly.
