### ISSUE TITLE
day4 TOC

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#23]
Hi Marcelo @zoccoler ,

in the rendered-book version the content of day4/napari-plugin session appears pretty empty:
https://biapol.github.io/Quantitative_Bio_Image_Analysis_with_Python_2022/day4c_crafting_napari_plugins/readme.html

![image](https://user-images.githubusercontent.com/12660498/195785024-cffeed98-8f5d-4e34-992f-710b9ea8bbd2.png)

However, there is content in that folder:
https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/blob/main/docs/day4c_crafting_napari_plugins/napari_cookiecutter.md

Would you mind checking the TOC?

Thanks!
Robert

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

Day4 TOC is updated and fixed now.

Best,
Marcelo
