### ISSUE TITLE
Link slides from the readme.md files

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#37]
Hi Johannes @jo-mueller ,

would you mind linking your PDF files from the readme.md files of the corresponding section? That makes it easier to find the slides  from the jupyter book.

Thanks,
Robert

**Comment by jo-mueller** [comment]
Should be in order now!

**Comment by haesleinhuepf** [comment]
I think so, too. Thanks @jo-mueller !
