### ISSUE TITLE
improve plotting exercise example

### ISSUE THREAD

**Issue by thawn** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#42]
the exercise example in `03_Plotting_distributions.ipynb`. does not really make sense. You should not plot area and intensity on the same ecdf plot. Try to find an example that makes more sense (e.g. plotting area of one kind vs are of another kind as ecdf)

**Comment by zoccoler** [comment]
Hi Till @thawn ,

Yes, I totally agree! Thanks for reporting this! The description of the exercise is actually wrong. The idea was to plot both files in a same plot, but area and intensities would go separate. 
In this example, the intensity ecdfs are very similar, but the area ecdfs are shifted, so it would be an interesting visual hint that areas could be different.
I will update this exercise once the course is finished to avoid Pull conflicts for the students.

Best,
Marcelo

**Comment by zoccoler** [comment]
Just fixed the exercise. 72a6aef1aec5a5c43b973708c1b21f3f5017de35
