### ISSUE TITLE
Remove teaching the LayerDataTuple in the napari exercise

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#49]
We should consider removing teaching the LayerDataTuple-exercise for three reasons:
* It's not necessary for a first napari plugin
* It's confusing
* Functions that return a LayerDataTuple are harder to reuse from Jupyter. 

I would remove this notebook: https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/blob/main/docs/day4c_crafting_napari_plugins/02_creating_widgets_from_functions_part2.ipynb

Instead it would be good if we can teach how to make functions that are resuable as napari plugin and as Jupyter notebook. Example:

```
def my_workflow(image:"napari.types.ImageData", sigma:float=1) -> "napari.types.LabelsData":

    # ...

    return label_image
```

**Comment by zoccoler** [comment]
I removed contents referring to LayerDataTuple and removed the mentioned notebook. 72a6aef1aec5a5c43b973708c1b21f3f5017de35

I kept importing napari data types because they seem to be more reliable (check [this comment](https://forum.image.sc/t/problem-with-adding-multiple-layers-at-once-as-list-napari-types-layerdatatuple-to/61293/8))

**Comment by haesleinhuepf** [comment]
Thanks for fixing this and thanks for the pointer! I'm generally using the `"napari.types.ImageData"` strings now. Maybe, we create some teaching materials for a future course where we can show `LayerDataTuple`, `napari.types.ImageData` `np.ndarray`, and others. I think it might make sense to elaborate on  the pros and cons of these different strategies. And I hope that there will be an advanced course on these things.

Thanks again!
