### ISSUE TITLE
use mamba instead of conda

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#50]
in this exercise:
https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/blob/main/docs/day4c_crafting_napari_plugins/04_napari_cookiecutter.md

... for setting up an environment.

**Comment by zoccoler** [comment]
I replaced conda by mamba in the mentioned markdown file. 72a6aef1aec5a5c43b973708c1b21f3f5017de35

**Comment by haesleinhuepf** [comment]
Awesome, thanks Marcelo @zoccoler !
